### ISSUE TITLE
Error en la unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales

### ISSUE THREAD

**Issue by wilnellia** [maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-wilnellia#1]
@hoyodepelenpito Tali, cuando estoy ejecutando la linea 111 de esta practica me da el siguiente error, a ver si me puede socorrer por favor. Entiendo que el requerimiento esta llenado como corresponde, sin embargo, persiste.
> miprovele <- raster::extract(mde, miprov)[[1]]
Error in st_cast_sfc_default(x) : list item(s) not of class sfg

**Comment by geofis** [comment]
@wilnellia Respondido [aquí](https://github.com/maestria-geotel-201902/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-MirelSIG/issues/2)

**Comment by geofis** [comment]
¿Podemos cerrar este *issue*?
